title: CS 4641 Project Proposal
description: A machine learning project aimed at predicting student dropout rates using academic data and supervised learning models.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
